# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: Swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- xcodebuild -scheme CSTestKit-Example -workspace Example/CSTestKit.xcworkspace -sdk iphonesimulator12.0 build test
- pod lib lint
