# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.2
language: Swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- brew update
- gem install cocoapods --pre # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- xcodebuild -scheme CSPDFReader-Example -workspace Example/CSPDFReader.xcworkspace -sdk iphonesimulator12.2 build test
- pod lib lint --no-clean
